// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package pinmux_reg_pkg;

  // Param list
  parameter int NMioPeriphIn = 1;
  parameter int NMioPeriphOut = 1;
  parameter int NMioPads = 4;
  parameter int NDioPads = 6;
  parameter int NWkupDetect = 1;
  parameter int WkupCntWidth = 8;
  parameter int NumAlerts = 1;

  // Address widths within the block
  parameter int BlockAw = 9;

  // Number of registers for every interface
  parameter int NumRegs = 69;

  // Alert indices
  typedef enum int {
    AlertFatalFaultIdx = 0
  } pinmux_alert_idx_t;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic        q;
    logic        qe;
  } pinmux_reg2hw_alert_test_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } pinmux_reg2hw_mio_periph_insel_mreg_t;

  typedef struct packed {
    logic [1:0]  q;
  } pinmux_reg2hw_mio_outsel_mreg_t;

  typedef struct packed {
    struct packed {
      logic [3:0]  q;
      logic        qe;
    } drive_strength;
    struct packed {
      logic [1:0]  q;
      logic        qe;
    } slew_rate;
    struct packed {
      logic        q;
      logic        qe;
    } input_disable;
    struct packed {
      logic        q;
      logic        qe;
    } od_en;
    struct packed {
      logic        q;
      logic        qe;
    } schmitt_en;
    struct packed {
      logic        q;
      logic        qe;
    } keeper_en;
    struct packed {
      logic        q;
      logic        qe;
    } pull_select;
    struct packed {
      logic        q;
      logic        qe;
    } pull_en;
    struct packed {
      logic        q;
      logic        qe;
    } virtual_od_en;
    struct packed {
      logic        q;
      logic        qe;
    } invert;
  } pinmux_reg2hw_mio_pad_attr_mreg_t;

  typedef struct packed {
    struct packed {
      logic [3:0]  q;
      logic        qe;
    } drive_strength;
    struct packed {
      logic [1:0]  q;
      logic        qe;
    } slew_rate;
    struct packed {
      logic        q;
      logic        qe;
    } input_disable;
    struct packed {
      logic        q;
      logic        qe;
    } od_en;
    struct packed {
      logic        q;
      logic        qe;
    } schmitt_en;
    struct packed {
      logic        q;
      logic        qe;
    } keeper_en;
    struct packed {
      logic        q;
      logic        qe;
    } pull_select;
    struct packed {
      logic        q;
      logic        qe;
    } pull_en;
    struct packed {
      logic        q;
      logic        qe;
    } virtual_od_en;
    struct packed {
      logic        q;
      logic        qe;
    } invert;
  } pinmux_reg2hw_dio_pad_attr_mreg_t;

  typedef struct packed {
    logic        q;
  } pinmux_reg2hw_mio_pad_sleep_status_mreg_t;

  typedef struct packed {
    logic        q;
  } pinmux_reg2hw_mio_pad_sleep_en_mreg_t;

  typedef struct packed {
    logic [1:0]  q;
  } pinmux_reg2hw_mio_pad_sleep_mode_mreg_t;

  typedef struct packed {
    logic        q;
  } pinmux_reg2hw_dio_pad_sleep_status_mreg_t;

  typedef struct packed {
    logic        q;
  } pinmux_reg2hw_dio_pad_sleep_en_mreg_t;

  typedef struct packed {
    logic [1:0]  q;
  } pinmux_reg2hw_dio_pad_sleep_mode_mreg_t;

  typedef struct packed {
    logic        q;
  } pinmux_reg2hw_wkup_detector_en_mreg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } miodio;
    struct packed {
      logic        q;
    } filter;
    struct packed {
      logic [2:0]  q;
    } mode;
  } pinmux_reg2hw_wkup_detector_mreg_t;

  typedef struct packed {
    logic [7:0]  q;
  } pinmux_reg2hw_wkup_detector_cnt_th_mreg_t;

  typedef struct packed {
    logic [2:0]  q;
  } pinmux_reg2hw_wkup_detector_padsel_mreg_t;

  typedef struct packed {
    logic        q;
  } pinmux_reg2hw_wkup_cause_mreg_t;

  typedef struct packed {
    struct packed {
      logic [3:0]  d;
    } drive_strength;
    struct packed {
      logic [1:0]  d;
    } slew_rate;
    struct packed {
      logic        d;
    } input_disable;
    struct packed {
      logic        d;
    } od_en;
    struct packed {
      logic        d;
    } schmitt_en;
    struct packed {
      logic        d;
    } keeper_en;
    struct packed {
      logic        d;
    } pull_select;
    struct packed {
      logic        d;
    } pull_en;
    struct packed {
      logic        d;
    } virtual_od_en;
    struct packed {
      logic        d;
    } invert;
  } pinmux_hw2reg_mio_pad_attr_mreg_t;

  typedef struct packed {
    struct packed {
      logic [3:0]  d;
    } drive_strength;
    struct packed {
      logic [1:0]  d;
    } slew_rate;
    struct packed {
      logic        d;
    } input_disable;
    struct packed {
      logic        d;
    } od_en;
    struct packed {
      logic        d;
    } schmitt_en;
    struct packed {
      logic        d;
    } keeper_en;
    struct packed {
      logic        d;
    } pull_select;
    struct packed {
      logic        d;
    } pull_en;
    struct packed {
      logic        d;
    } virtual_od_en;
    struct packed {
      logic        d;
    } invert;
  } pinmux_hw2reg_dio_pad_attr_mreg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } pinmux_hw2reg_mio_pad_sleep_status_mreg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } pinmux_hw2reg_dio_pad_sleep_status_mreg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } pinmux_hw2reg_wkup_cause_mreg_t;

  // Register -> HW type
  typedef struct packed {
    pinmux_reg2hw_alert_test_reg_t alert_test; // [310:309]
    pinmux_reg2hw_mio_periph_insel_mreg_t [0:0] mio_periph_insel; // [308:306]
    pinmux_reg2hw_mio_outsel_mreg_t [3:0] mio_outsel; // [305:298]
    pinmux_reg2hw_mio_pad_attr_mreg_t [3:0] mio_pad_attr; // [297:202]
    pinmux_reg2hw_dio_pad_attr_mreg_t [5:0] dio_pad_attr; // [201:58]
    pinmux_reg2hw_mio_pad_sleep_status_mreg_t [3:0] mio_pad_sleep_status; // [57:54]
    pinmux_reg2hw_mio_pad_sleep_en_mreg_t [3:0] mio_pad_sleep_en; // [53:50]
    pinmux_reg2hw_mio_pad_sleep_mode_mreg_t [3:0] mio_pad_sleep_mode; // [49:42]
    pinmux_reg2hw_dio_pad_sleep_status_mreg_t [5:0] dio_pad_sleep_status; // [41:36]
    pinmux_reg2hw_dio_pad_sleep_en_mreg_t [5:0] dio_pad_sleep_en; // [35:30]
    pinmux_reg2hw_dio_pad_sleep_mode_mreg_t [5:0] dio_pad_sleep_mode; // [29:18]
    pinmux_reg2hw_wkup_detector_en_mreg_t [0:0] wkup_detector_en; // [17:17]
    pinmux_reg2hw_wkup_detector_mreg_t [0:0] wkup_detector; // [16:12]
    pinmux_reg2hw_wkup_detector_cnt_th_mreg_t [0:0] wkup_detector_cnt_th; // [11:4]
    pinmux_reg2hw_wkup_detector_padsel_mreg_t [0:0] wkup_detector_padsel; // [3:1]
    pinmux_reg2hw_wkup_cause_mreg_t [0:0] wkup_cause; // [0:0]
  } pinmux_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    pinmux_hw2reg_mio_pad_attr_mreg_t [3:0] mio_pad_attr; // [161:106]
    pinmux_hw2reg_dio_pad_attr_mreg_t [5:0] dio_pad_attr; // [105:22]
    pinmux_hw2reg_mio_pad_sleep_status_mreg_t [3:0] mio_pad_sleep_status; // [21:14]
    pinmux_hw2reg_dio_pad_sleep_status_mreg_t [5:0] dio_pad_sleep_status; // [13:2]
    pinmux_hw2reg_wkup_cause_mreg_t [0:0] wkup_cause; // [1:0]
  } pinmux_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] PINMUX_ALERT_TEST_OFFSET = 9'h 0;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PERIPH_INSEL_REGWEN_OFFSET = 9'h 4;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PERIPH_INSEL_OFFSET = 9'h 8;
  parameter logic [BlockAw-1:0] PINMUX_MIO_OUTSEL_REGWEN_0_OFFSET = 9'h c;
  parameter logic [BlockAw-1:0] PINMUX_MIO_OUTSEL_REGWEN_1_OFFSET = 9'h 10;
  parameter logic [BlockAw-1:0] PINMUX_MIO_OUTSEL_REGWEN_2_OFFSET = 9'h 14;
  parameter logic [BlockAw-1:0] PINMUX_MIO_OUTSEL_REGWEN_3_OFFSET = 9'h 18;
  parameter logic [BlockAw-1:0] PINMUX_MIO_OUTSEL_0_OFFSET = 9'h 1c;
  parameter logic [BlockAw-1:0] PINMUX_MIO_OUTSEL_1_OFFSET = 9'h 20;
  parameter logic [BlockAw-1:0] PINMUX_MIO_OUTSEL_2_OFFSET = 9'h 24;
  parameter logic [BlockAw-1:0] PINMUX_MIO_OUTSEL_3_OFFSET = 9'h 28;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_ATTR_REGWEN_0_OFFSET = 9'h 2c;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_ATTR_REGWEN_1_OFFSET = 9'h 30;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_ATTR_REGWEN_2_OFFSET = 9'h 34;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_ATTR_REGWEN_3_OFFSET = 9'h 38;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_ATTR_0_OFFSET = 9'h 3c;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_ATTR_1_OFFSET = 9'h 40;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_ATTR_2_OFFSET = 9'h 44;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_ATTR_3_OFFSET = 9'h 48;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_ATTR_REGWEN_0_OFFSET = 9'h 4c;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_ATTR_REGWEN_1_OFFSET = 9'h 50;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_ATTR_REGWEN_2_OFFSET = 9'h 54;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_ATTR_REGWEN_3_OFFSET = 9'h 58;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_ATTR_REGWEN_4_OFFSET = 9'h 5c;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_ATTR_REGWEN_5_OFFSET = 9'h 60;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_ATTR_0_OFFSET = 9'h 64;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_ATTR_1_OFFSET = 9'h 68;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_ATTR_2_OFFSET = 9'h 6c;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_ATTR_3_OFFSET = 9'h 70;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_ATTR_4_OFFSET = 9'h 74;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_ATTR_5_OFFSET = 9'h 78;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_SLEEP_STATUS_OFFSET = 9'h 7c;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_SLEEP_REGWEN_0_OFFSET = 9'h 80;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_SLEEP_REGWEN_1_OFFSET = 9'h 84;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_SLEEP_REGWEN_2_OFFSET = 9'h 88;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_SLEEP_REGWEN_3_OFFSET = 9'h 8c;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_SLEEP_EN_0_OFFSET = 9'h 90;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_SLEEP_EN_1_OFFSET = 9'h 94;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_SLEEP_EN_2_OFFSET = 9'h 98;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_SLEEP_EN_3_OFFSET = 9'h 9c;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_SLEEP_MODE_0_OFFSET = 9'h a0;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_SLEEP_MODE_1_OFFSET = 9'h a4;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_SLEEP_MODE_2_OFFSET = 9'h a8;
  parameter logic [BlockAw-1:0] PINMUX_MIO_PAD_SLEEP_MODE_3_OFFSET = 9'h ac;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_STATUS_OFFSET = 9'h b0;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_REGWEN_0_OFFSET = 9'h b4;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_REGWEN_1_OFFSET = 9'h b8;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_REGWEN_2_OFFSET = 9'h bc;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_REGWEN_3_OFFSET = 9'h c0;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_REGWEN_4_OFFSET = 9'h c4;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_REGWEN_5_OFFSET = 9'h c8;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_EN_0_OFFSET = 9'h cc;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_EN_1_OFFSET = 9'h d0;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_EN_2_OFFSET = 9'h d4;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_EN_3_OFFSET = 9'h d8;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_EN_4_OFFSET = 9'h dc;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_EN_5_OFFSET = 9'h e0;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_MODE_0_OFFSET = 9'h e4;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_MODE_1_OFFSET = 9'h e8;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_MODE_2_OFFSET = 9'h ec;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_MODE_3_OFFSET = 9'h f0;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_MODE_4_OFFSET = 9'h f4;
  parameter logic [BlockAw-1:0] PINMUX_DIO_PAD_SLEEP_MODE_5_OFFSET = 9'h f8;
  parameter logic [BlockAw-1:0] PINMUX_WKUP_DETECTOR_REGWEN_OFFSET = 9'h fc;
  parameter logic [BlockAw-1:0] PINMUX_WKUP_DETECTOR_EN_OFFSET = 9'h 100;
  parameter logic [BlockAw-1:0] PINMUX_WKUP_DETECTOR_OFFSET = 9'h 104;
  parameter logic [BlockAw-1:0] PINMUX_WKUP_DETECTOR_CNT_TH_OFFSET = 9'h 108;
  parameter logic [BlockAw-1:0] PINMUX_WKUP_DETECTOR_PADSEL_OFFSET = 9'h 10c;
  parameter logic [BlockAw-1:0] PINMUX_WKUP_CAUSE_OFFSET = 9'h 110;

  // Reset values for hwext registers and their fields
  parameter logic [0:0] PINMUX_ALERT_TEST_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_ALERT_TEST_FATAL_FAULT_RESVAL = 1'h 0;
  parameter logic [23:0] PINMUX_MIO_PAD_ATTR_0_RESVAL = 24'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_0_INVERT_0_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_0_VIRTUAL_OD_EN_0_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_0_PULL_EN_0_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_0_PULL_SELECT_0_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_0_KEEPER_EN_0_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_0_SCHMITT_EN_0_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_0_OD_EN_0_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_0_INPUT_DISABLE_0_RESVAL = 1'h 0;
  parameter logic [1:0] PINMUX_MIO_PAD_ATTR_0_SLEW_RATE_0_RESVAL = 2'h 0;
  parameter logic [3:0] PINMUX_MIO_PAD_ATTR_0_DRIVE_STRENGTH_0_RESVAL = 4'h 0;
  parameter logic [23:0] PINMUX_MIO_PAD_ATTR_1_RESVAL = 24'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_1_INVERT_1_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_1_VIRTUAL_OD_EN_1_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_1_PULL_EN_1_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_1_PULL_SELECT_1_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_1_KEEPER_EN_1_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_1_SCHMITT_EN_1_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_1_OD_EN_1_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_1_INPUT_DISABLE_1_RESVAL = 1'h 0;
  parameter logic [1:0] PINMUX_MIO_PAD_ATTR_1_SLEW_RATE_1_RESVAL = 2'h 0;
  parameter logic [3:0] PINMUX_MIO_PAD_ATTR_1_DRIVE_STRENGTH_1_RESVAL = 4'h 0;
  parameter logic [23:0] PINMUX_MIO_PAD_ATTR_2_RESVAL = 24'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_2_INVERT_2_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_2_VIRTUAL_OD_EN_2_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_2_PULL_EN_2_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_2_PULL_SELECT_2_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_2_KEEPER_EN_2_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_2_SCHMITT_EN_2_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_2_OD_EN_2_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_2_INPUT_DISABLE_2_RESVAL = 1'h 0;
  parameter logic [1:0] PINMUX_MIO_PAD_ATTR_2_SLEW_RATE_2_RESVAL = 2'h 0;
  parameter logic [3:0] PINMUX_MIO_PAD_ATTR_2_DRIVE_STRENGTH_2_RESVAL = 4'h 0;
  parameter logic [23:0] PINMUX_MIO_PAD_ATTR_3_RESVAL = 24'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_3_INVERT_3_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_3_VIRTUAL_OD_EN_3_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_3_PULL_EN_3_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_3_PULL_SELECT_3_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_3_KEEPER_EN_3_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_3_SCHMITT_EN_3_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_3_OD_EN_3_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_MIO_PAD_ATTR_3_INPUT_DISABLE_3_RESVAL = 1'h 0;
  parameter logic [1:0] PINMUX_MIO_PAD_ATTR_3_SLEW_RATE_3_RESVAL = 2'h 0;
  parameter logic [3:0] PINMUX_MIO_PAD_ATTR_3_DRIVE_STRENGTH_3_RESVAL = 4'h 0;
  parameter logic [23:0] PINMUX_DIO_PAD_ATTR_0_RESVAL = 24'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_0_INVERT_0_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_0_VIRTUAL_OD_EN_0_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_0_PULL_EN_0_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_0_PULL_SELECT_0_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_0_KEEPER_EN_0_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_0_SCHMITT_EN_0_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_0_OD_EN_0_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_0_INPUT_DISABLE_0_RESVAL = 1'h 0;
  parameter logic [1:0] PINMUX_DIO_PAD_ATTR_0_SLEW_RATE_0_RESVAL = 2'h 0;
  parameter logic [3:0] PINMUX_DIO_PAD_ATTR_0_DRIVE_STRENGTH_0_RESVAL = 4'h 0;
  parameter logic [23:0] PINMUX_DIO_PAD_ATTR_1_RESVAL = 24'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_1_INVERT_1_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_1_VIRTUAL_OD_EN_1_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_1_PULL_EN_1_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_1_PULL_SELECT_1_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_1_KEEPER_EN_1_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_1_SCHMITT_EN_1_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_1_OD_EN_1_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_1_INPUT_DISABLE_1_RESVAL = 1'h 0;
  parameter logic [1:0] PINMUX_DIO_PAD_ATTR_1_SLEW_RATE_1_RESVAL = 2'h 0;
  parameter logic [3:0] PINMUX_DIO_PAD_ATTR_1_DRIVE_STRENGTH_1_RESVAL = 4'h 0;
  parameter logic [23:0] PINMUX_DIO_PAD_ATTR_2_RESVAL = 24'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_2_INVERT_2_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_2_VIRTUAL_OD_EN_2_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_2_PULL_EN_2_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_2_PULL_SELECT_2_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_2_KEEPER_EN_2_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_2_SCHMITT_EN_2_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_2_OD_EN_2_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_2_INPUT_DISABLE_2_RESVAL = 1'h 0;
  parameter logic [1:0] PINMUX_DIO_PAD_ATTR_2_SLEW_RATE_2_RESVAL = 2'h 0;
  parameter logic [3:0] PINMUX_DIO_PAD_ATTR_2_DRIVE_STRENGTH_2_RESVAL = 4'h 0;
  parameter logic [23:0] PINMUX_DIO_PAD_ATTR_3_RESVAL = 24'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_3_INVERT_3_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_3_VIRTUAL_OD_EN_3_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_3_PULL_EN_3_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_3_PULL_SELECT_3_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_3_KEEPER_EN_3_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_3_SCHMITT_EN_3_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_3_OD_EN_3_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_3_INPUT_DISABLE_3_RESVAL = 1'h 0;
  parameter logic [1:0] PINMUX_DIO_PAD_ATTR_3_SLEW_RATE_3_RESVAL = 2'h 0;
  parameter logic [3:0] PINMUX_DIO_PAD_ATTR_3_DRIVE_STRENGTH_3_RESVAL = 4'h 0;
  parameter logic [23:0] PINMUX_DIO_PAD_ATTR_4_RESVAL = 24'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_4_INVERT_4_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_4_VIRTUAL_OD_EN_4_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_4_PULL_EN_4_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_4_PULL_SELECT_4_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_4_KEEPER_EN_4_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_4_SCHMITT_EN_4_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_4_OD_EN_4_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_4_INPUT_DISABLE_4_RESVAL = 1'h 0;
  parameter logic [1:0] PINMUX_DIO_PAD_ATTR_4_SLEW_RATE_4_RESVAL = 2'h 0;
  parameter logic [3:0] PINMUX_DIO_PAD_ATTR_4_DRIVE_STRENGTH_4_RESVAL = 4'h 0;
  parameter logic [23:0] PINMUX_DIO_PAD_ATTR_5_RESVAL = 24'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_5_INVERT_5_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_5_VIRTUAL_OD_EN_5_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_5_PULL_EN_5_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_5_PULL_SELECT_5_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_5_KEEPER_EN_5_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_5_SCHMITT_EN_5_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_5_OD_EN_5_RESVAL = 1'h 0;
  parameter logic [0:0] PINMUX_DIO_PAD_ATTR_5_INPUT_DISABLE_5_RESVAL = 1'h 0;
  parameter logic [1:0] PINMUX_DIO_PAD_ATTR_5_SLEW_RATE_5_RESVAL = 2'h 0;
  parameter logic [3:0] PINMUX_DIO_PAD_ATTR_5_DRIVE_STRENGTH_5_RESVAL = 4'h 0;

  // Register index
  typedef enum int {
    PINMUX_ALERT_TEST,
    PINMUX_MIO_PERIPH_INSEL_REGWEN,
    PINMUX_MIO_PERIPH_INSEL,
    PINMUX_MIO_OUTSEL_REGWEN_0,
    PINMUX_MIO_OUTSEL_REGWEN_1,
    PINMUX_MIO_OUTSEL_REGWEN_2,
    PINMUX_MIO_OUTSEL_REGWEN_3,
    PINMUX_MIO_OUTSEL_0,
    PINMUX_MIO_OUTSEL_1,
    PINMUX_MIO_OUTSEL_2,
    PINMUX_MIO_OUTSEL_3,
    PINMUX_MIO_PAD_ATTR_REGWEN_0,
    PINMUX_MIO_PAD_ATTR_REGWEN_1,
    PINMUX_MIO_PAD_ATTR_REGWEN_2,
    PINMUX_MIO_PAD_ATTR_REGWEN_3,
    PINMUX_MIO_PAD_ATTR_0,
    PINMUX_MIO_PAD_ATTR_1,
    PINMUX_MIO_PAD_ATTR_2,
    PINMUX_MIO_PAD_ATTR_3,
    PINMUX_DIO_PAD_ATTR_REGWEN_0,
    PINMUX_DIO_PAD_ATTR_REGWEN_1,
    PINMUX_DIO_PAD_ATTR_REGWEN_2,
    PINMUX_DIO_PAD_ATTR_REGWEN_3,
    PINMUX_DIO_PAD_ATTR_REGWEN_4,
    PINMUX_DIO_PAD_ATTR_REGWEN_5,
    PINMUX_DIO_PAD_ATTR_0,
    PINMUX_DIO_PAD_ATTR_1,
    PINMUX_DIO_PAD_ATTR_2,
    PINMUX_DIO_PAD_ATTR_3,
    PINMUX_DIO_PAD_ATTR_4,
    PINMUX_DIO_PAD_ATTR_5,
    PINMUX_MIO_PAD_SLEEP_STATUS,
    PINMUX_MIO_PAD_SLEEP_REGWEN_0,
    PINMUX_MIO_PAD_SLEEP_REGWEN_1,
    PINMUX_MIO_PAD_SLEEP_REGWEN_2,
    PINMUX_MIO_PAD_SLEEP_REGWEN_3,
    PINMUX_MIO_PAD_SLEEP_EN_0,
    PINMUX_MIO_PAD_SLEEP_EN_1,
    PINMUX_MIO_PAD_SLEEP_EN_2,
    PINMUX_MIO_PAD_SLEEP_EN_3,
    PINMUX_MIO_PAD_SLEEP_MODE_0,
    PINMUX_MIO_PAD_SLEEP_MODE_1,
    PINMUX_MIO_PAD_SLEEP_MODE_2,
    PINMUX_MIO_PAD_SLEEP_MODE_3,
    PINMUX_DIO_PAD_SLEEP_STATUS,
    PINMUX_DIO_PAD_SLEEP_REGWEN_0,
    PINMUX_DIO_PAD_SLEEP_REGWEN_1,
    PINMUX_DIO_PAD_SLEEP_REGWEN_2,
    PINMUX_DIO_PAD_SLEEP_REGWEN_3,
    PINMUX_DIO_PAD_SLEEP_REGWEN_4,
    PINMUX_DIO_PAD_SLEEP_REGWEN_5,
    PINMUX_DIO_PAD_SLEEP_EN_0,
    PINMUX_DIO_PAD_SLEEP_EN_1,
    PINMUX_DIO_PAD_SLEEP_EN_2,
    PINMUX_DIO_PAD_SLEEP_EN_3,
    PINMUX_DIO_PAD_SLEEP_EN_4,
    PINMUX_DIO_PAD_SLEEP_EN_5,
    PINMUX_DIO_PAD_SLEEP_MODE_0,
    PINMUX_DIO_PAD_SLEEP_MODE_1,
    PINMUX_DIO_PAD_SLEEP_MODE_2,
    PINMUX_DIO_PAD_SLEEP_MODE_3,
    PINMUX_DIO_PAD_SLEEP_MODE_4,
    PINMUX_DIO_PAD_SLEEP_MODE_5,
    PINMUX_WKUP_DETECTOR_REGWEN,
    PINMUX_WKUP_DETECTOR_EN,
    PINMUX_WKUP_DETECTOR,
    PINMUX_WKUP_DETECTOR_CNT_TH,
    PINMUX_WKUP_DETECTOR_PADSEL,
    PINMUX_WKUP_CAUSE
  } pinmux_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] PINMUX_PERMIT [69] = '{
    4'b 0001, // index[ 0] PINMUX_ALERT_TEST
    4'b 0001, // index[ 1] PINMUX_MIO_PERIPH_INSEL_REGWEN
    4'b 0001, // index[ 2] PINMUX_MIO_PERIPH_INSEL
    4'b 0001, // index[ 3] PINMUX_MIO_OUTSEL_REGWEN_0
    4'b 0001, // index[ 4] PINMUX_MIO_OUTSEL_REGWEN_1
    4'b 0001, // index[ 5] PINMUX_MIO_OUTSEL_REGWEN_2
    4'b 0001, // index[ 6] PINMUX_MIO_OUTSEL_REGWEN_3
    4'b 0001, // index[ 7] PINMUX_MIO_OUTSEL_0
    4'b 0001, // index[ 8] PINMUX_MIO_OUTSEL_1
    4'b 0001, // index[ 9] PINMUX_MIO_OUTSEL_2
    4'b 0001, // index[10] PINMUX_MIO_OUTSEL_3
    4'b 0001, // index[11] PINMUX_MIO_PAD_ATTR_REGWEN_0
    4'b 0001, // index[12] PINMUX_MIO_PAD_ATTR_REGWEN_1
    4'b 0001, // index[13] PINMUX_MIO_PAD_ATTR_REGWEN_2
    4'b 0001, // index[14] PINMUX_MIO_PAD_ATTR_REGWEN_3
    4'b 0111, // index[15] PINMUX_MIO_PAD_ATTR_0
    4'b 0111, // index[16] PINMUX_MIO_PAD_ATTR_1
    4'b 0111, // index[17] PINMUX_MIO_PAD_ATTR_2
    4'b 0111, // index[18] PINMUX_MIO_PAD_ATTR_3
    4'b 0001, // index[19] PINMUX_DIO_PAD_ATTR_REGWEN_0
    4'b 0001, // index[20] PINMUX_DIO_PAD_ATTR_REGWEN_1
    4'b 0001, // index[21] PINMUX_DIO_PAD_ATTR_REGWEN_2
    4'b 0001, // index[22] PINMUX_DIO_PAD_ATTR_REGWEN_3
    4'b 0001, // index[23] PINMUX_DIO_PAD_ATTR_REGWEN_4
    4'b 0001, // index[24] PINMUX_DIO_PAD_ATTR_REGWEN_5
    4'b 0111, // index[25] PINMUX_DIO_PAD_ATTR_0
    4'b 0111, // index[26] PINMUX_DIO_PAD_ATTR_1
    4'b 0111, // index[27] PINMUX_DIO_PAD_ATTR_2
    4'b 0111, // index[28] PINMUX_DIO_PAD_ATTR_3
    4'b 0111, // index[29] PINMUX_DIO_PAD_ATTR_4
    4'b 0111, // index[30] PINMUX_DIO_PAD_ATTR_5
    4'b 0001, // index[31] PINMUX_MIO_PAD_SLEEP_STATUS
    4'b 0001, // index[32] PINMUX_MIO_PAD_SLEEP_REGWEN_0
    4'b 0001, // index[33] PINMUX_MIO_PAD_SLEEP_REGWEN_1
    4'b 0001, // index[34] PINMUX_MIO_PAD_SLEEP_REGWEN_2
    4'b 0001, // index[35] PINMUX_MIO_PAD_SLEEP_REGWEN_3
    4'b 0001, // index[36] PINMUX_MIO_PAD_SLEEP_EN_0
    4'b 0001, // index[37] PINMUX_MIO_PAD_SLEEP_EN_1
    4'b 0001, // index[38] PINMUX_MIO_PAD_SLEEP_EN_2
    4'b 0001, // index[39] PINMUX_MIO_PAD_SLEEP_EN_3
    4'b 0001, // index[40] PINMUX_MIO_PAD_SLEEP_MODE_0
    4'b 0001, // index[41] PINMUX_MIO_PAD_SLEEP_MODE_1
    4'b 0001, // index[42] PINMUX_MIO_PAD_SLEEP_MODE_2
    4'b 0001, // index[43] PINMUX_MIO_PAD_SLEEP_MODE_3
    4'b 0001, // index[44] PINMUX_DIO_PAD_SLEEP_STATUS
    4'b 0001, // index[45] PINMUX_DIO_PAD_SLEEP_REGWEN_0
    4'b 0001, // index[46] PINMUX_DIO_PAD_SLEEP_REGWEN_1
    4'b 0001, // index[47] PINMUX_DIO_PAD_SLEEP_REGWEN_2
    4'b 0001, // index[48] PINMUX_DIO_PAD_SLEEP_REGWEN_3
    4'b 0001, // index[49] PINMUX_DIO_PAD_SLEEP_REGWEN_4
    4'b 0001, // index[50] PINMUX_DIO_PAD_SLEEP_REGWEN_5
    4'b 0001, // index[51] PINMUX_DIO_PAD_SLEEP_EN_0
    4'b 0001, // index[52] PINMUX_DIO_PAD_SLEEP_EN_1
    4'b 0001, // index[53] PINMUX_DIO_PAD_SLEEP_EN_2
    4'b 0001, // index[54] PINMUX_DIO_PAD_SLEEP_EN_3
    4'b 0001, // index[55] PINMUX_DIO_PAD_SLEEP_EN_4
    4'b 0001, // index[56] PINMUX_DIO_PAD_SLEEP_EN_5
    4'b 0001, // index[57] PINMUX_DIO_PAD_SLEEP_MODE_0
    4'b 0001, // index[58] PINMUX_DIO_PAD_SLEEP_MODE_1
    4'b 0001, // index[59] PINMUX_DIO_PAD_SLEEP_MODE_2
    4'b 0001, // index[60] PINMUX_DIO_PAD_SLEEP_MODE_3
    4'b 0001, // index[61] PINMUX_DIO_PAD_SLEEP_MODE_4
    4'b 0001, // index[62] PINMUX_DIO_PAD_SLEEP_MODE_5
    4'b 0001, // index[63] PINMUX_WKUP_DETECTOR_REGWEN
    4'b 0001, // index[64] PINMUX_WKUP_DETECTOR_EN
    4'b 0001, // index[65] PINMUX_WKUP_DETECTOR
    4'b 0001, // index[66] PINMUX_WKUP_DETECTOR_CNT_TH
    4'b 0001, // index[67] PINMUX_WKUP_DETECTOR_PADSEL
    4'b 0001  // index[68] PINMUX_WKUP_CAUSE
  };

endpackage
