// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_peri package generated by `tlgen.py` tool

package tl_peri_pkg;

  localparam logic [31:0] ADDR_SPACE_UART0      = 32'h 40000000;
  localparam logic [31:0] ADDR_SPACE_SPI_DEVICE = 32'h 40050000;
  localparam logic [31:0] ADDR_SPACE_RV_TIMER   = 32'h 40100000;
  localparam logic [31:0] ADDR_SPACE_PWRMGR_AON = 32'h 40400000;
  localparam logic [31:0] ADDR_SPACE_RSTMGR_AON = 32'h 40410000;
  localparam logic [31:0] ADDR_SPACE_CLKMGR_AON = 32'h 40420000;
  localparam logic [31:0] ADDR_SPACE_PINMUX_AON = 32'h 40460000;

  localparam logic [31:0] ADDR_MASK_UART0      = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_SPI_DEVICE = 32'h 00001fff;
  localparam logic [31:0] ADDR_MASK_RV_TIMER   = 32'h 000001ff;
  localparam logic [31:0] ADDR_MASK_PWRMGR_AON = 32'h 0000007f;
  localparam logic [31:0] ADDR_MASK_RSTMGR_AON = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_CLKMGR_AON = 32'h 0000003f;
  localparam logic [31:0] ADDR_MASK_PINMUX_AON = 32'h 000001ff;

  localparam int N_HOST   = 1;
  localparam int N_DEVICE = 7;

  typedef enum int {
    TlUart0 = 0,
    TlSpiDevice = 1,
    TlRvTimer = 2,
    TlPwrmgrAon = 3,
    TlRstmgrAon = 4,
    TlClkmgrAon = 5,
    TlPinmuxAon = 6
  } tl_device_e;

  typedef enum int {
    TlMain = 0
  } tl_host_e;

endpackage
