// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package rv_plic_reg_pkg;

  // Param list
  parameter int NumSrc = 19;
  parameter int NumTarget = 1;
  parameter int PrioWidth = 2;
  parameter int NumAlerts = 1;

  // Address widths within the block
  parameter int BlockAw = 27;

  // Number of registers for every interface
  parameter int NumRegs = 25;

  // Alert indices
  typedef enum int {
    AlertFatalFaultIdx = 0
  } rv_plic_alert_idx_t;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [1:0]  q;
  } rv_plic_reg2hw_prio_mreg_t;

  typedef struct packed {
    logic        q;
  } rv_plic_reg2hw_ie0_mreg_t;

  typedef struct packed {
    logic [1:0]  q;
  } rv_plic_reg2hw_threshold0_reg_t;

  typedef struct packed {
    logic [4:0]  q;
    logic        qe;
    logic        re;
  } rv_plic_reg2hw_cc0_reg_t;

  typedef struct packed {
    logic        q;
  } rv_plic_reg2hw_msip0_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } rv_plic_reg2hw_alert_test_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } rv_plic_hw2reg_ip_mreg_t;

  typedef struct packed {
    logic [4:0]  d;
  } rv_plic_hw2reg_cc0_reg_t;

  // Register -> HW type
  typedef struct packed {
    rv_plic_reg2hw_prio_mreg_t [18:0] prio; // [68:31]
    rv_plic_reg2hw_ie0_mreg_t [18:0] ie0; // [30:12]
    rv_plic_reg2hw_threshold0_reg_t threshold0; // [11:10]
    rv_plic_reg2hw_cc0_reg_t cc0; // [9:3]
    rv_plic_reg2hw_msip0_reg_t msip0; // [2:2]
    rv_plic_reg2hw_alert_test_reg_t alert_test; // [1:0]
  } rv_plic_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    rv_plic_hw2reg_ip_mreg_t [18:0] ip; // [42:5]
    rv_plic_hw2reg_cc0_reg_t cc0; // [4:0]
  } rv_plic_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_0_OFFSET = 27'h 0;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_1_OFFSET = 27'h 4;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_2_OFFSET = 27'h 8;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_3_OFFSET = 27'h c;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_4_OFFSET = 27'h 10;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_5_OFFSET = 27'h 14;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_6_OFFSET = 27'h 18;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_7_OFFSET = 27'h 1c;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_8_OFFSET = 27'h 20;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_9_OFFSET = 27'h 24;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_10_OFFSET = 27'h 28;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_11_OFFSET = 27'h 2c;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_12_OFFSET = 27'h 30;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_13_OFFSET = 27'h 34;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_14_OFFSET = 27'h 38;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_15_OFFSET = 27'h 3c;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_16_OFFSET = 27'h 40;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_17_OFFSET = 27'h 44;
  parameter logic [BlockAw-1:0] RV_PLIC_PRIO_18_OFFSET = 27'h 48;
  parameter logic [BlockAw-1:0] RV_PLIC_IP_OFFSET = 27'h 1000;
  parameter logic [BlockAw-1:0] RV_PLIC_IE0_OFFSET = 27'h 2000;
  parameter logic [BlockAw-1:0] RV_PLIC_THRESHOLD0_OFFSET = 27'h 200000;
  parameter logic [BlockAw-1:0] RV_PLIC_CC0_OFFSET = 27'h 200004;
  parameter logic [BlockAw-1:0] RV_PLIC_MSIP0_OFFSET = 27'h 4000000;
  parameter logic [BlockAw-1:0] RV_PLIC_ALERT_TEST_OFFSET = 27'h 4004000;

  // Reset values for hwext registers and their fields
  parameter logic [4:0] RV_PLIC_CC0_RESVAL = 5'h 0;
  parameter logic [0:0] RV_PLIC_ALERT_TEST_RESVAL = 1'h 0;

  // Register index
  typedef enum int {
    RV_PLIC_PRIO_0,
    RV_PLIC_PRIO_1,
    RV_PLIC_PRIO_2,
    RV_PLIC_PRIO_3,
    RV_PLIC_PRIO_4,
    RV_PLIC_PRIO_5,
    RV_PLIC_PRIO_6,
    RV_PLIC_PRIO_7,
    RV_PLIC_PRIO_8,
    RV_PLIC_PRIO_9,
    RV_PLIC_PRIO_10,
    RV_PLIC_PRIO_11,
    RV_PLIC_PRIO_12,
    RV_PLIC_PRIO_13,
    RV_PLIC_PRIO_14,
    RV_PLIC_PRIO_15,
    RV_PLIC_PRIO_16,
    RV_PLIC_PRIO_17,
    RV_PLIC_PRIO_18,
    RV_PLIC_IP,
    RV_PLIC_IE0,
    RV_PLIC_THRESHOLD0,
    RV_PLIC_CC0,
    RV_PLIC_MSIP0,
    RV_PLIC_ALERT_TEST
  } rv_plic_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] RV_PLIC_PERMIT [25] = '{
    4'b 0001, // index[ 0] RV_PLIC_PRIO_0
    4'b 0001, // index[ 1] RV_PLIC_PRIO_1
    4'b 0001, // index[ 2] RV_PLIC_PRIO_2
    4'b 0001, // index[ 3] RV_PLIC_PRIO_3
    4'b 0001, // index[ 4] RV_PLIC_PRIO_4
    4'b 0001, // index[ 5] RV_PLIC_PRIO_5
    4'b 0001, // index[ 6] RV_PLIC_PRIO_6
    4'b 0001, // index[ 7] RV_PLIC_PRIO_7
    4'b 0001, // index[ 8] RV_PLIC_PRIO_8
    4'b 0001, // index[ 9] RV_PLIC_PRIO_9
    4'b 0001, // index[10] RV_PLIC_PRIO_10
    4'b 0001, // index[11] RV_PLIC_PRIO_11
    4'b 0001, // index[12] RV_PLIC_PRIO_12
    4'b 0001, // index[13] RV_PLIC_PRIO_13
    4'b 0001, // index[14] RV_PLIC_PRIO_14
    4'b 0001, // index[15] RV_PLIC_PRIO_15
    4'b 0001, // index[16] RV_PLIC_PRIO_16
    4'b 0001, // index[17] RV_PLIC_PRIO_17
    4'b 0001, // index[18] RV_PLIC_PRIO_18
    4'b 0111, // index[19] RV_PLIC_IP
    4'b 0111, // index[20] RV_PLIC_IE0
    4'b 0001, // index[21] RV_PLIC_THRESHOLD0
    4'b 0001, // index[22] RV_PLIC_CC0
    4'b 0001, // index[23] RV_PLIC_MSIP0
    4'b 0001  // index[24] RV_PLIC_ALERT_TEST
  };

endpackage
