// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// UVM Registers auto-generated by `reggen` containing data structure
package rv_dm_regs_ral_pkg;
  // dep packages
  import uvm_pkg::*;
  import dv_base_reg_pkg::*;

  // macro includes
  `include "uvm_macros.svh"

  // Forward declare all register/memory/block classes
  typedef class rv_dm_regs_reg_alert_test;
  typedef class rv_dm_regs_reg_late_debug_enable_regwen;
  typedef class rv_dm_regs_reg_late_debug_enable;
  typedef class rv_dm_regs_reg_block;

  class rv_dm_regs_reg_alert_test extends dv_base_reg;
    // fields
    rand dv_base_reg_field fatal_fault;

    `uvm_object_utils(rv_dm_regs_reg_alert_test)

    function new(string       name = "",
                 int unsigned n_bits = 32,
                 int          has_coverage = UVM_NO_COVERAGE);
      super.new(name, n_bits, has_coverage);
    endfunction : new

    virtual function void build(csr_excl_item csr_excl = null);
      fatal_fault =
          (dv_base_reg_field::
           type_id::create("fatal_fault"));
      fatal_fault.configure(
        .parent(this),
        .size(1),
        .lsb_pos(0),
        .access("WO"),
        .mubi_access("NONE"),
        .volatile(0),
        .reset(32'h0),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));

      fatal_fault.set_original_access("WO");
      set_is_ext_reg(1);
    endfunction : build
  endclass : rv_dm_regs_reg_alert_test

  class rv_dm_regs_reg_late_debug_enable_regwen extends dv_base_reg;
    // fields
    rand dv_base_reg_field late_debug_enable_regwen;

    `uvm_object_utils(rv_dm_regs_reg_late_debug_enable_regwen)

    function new(string       name = "",
                 int unsigned n_bits = 32,
                 int          has_coverage = UVM_NO_COVERAGE);
      super.new(name, n_bits, has_coverage);
    endfunction : new

    virtual function void build(csr_excl_item csr_excl = null);
      late_debug_enable_regwen =
          (dv_base_reg_field::
           type_id::create("late_debug_enable_regwen"));
      late_debug_enable_regwen.configure(
        .parent(this),
        .size(1),
        .lsb_pos(0),
        .access("W0C"),
        .mubi_access("NONE"),
        .volatile(0),
        .reset(32'h1),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));

      late_debug_enable_regwen.set_original_access("W0C");
    endfunction : build
  endclass : rv_dm_regs_reg_late_debug_enable_regwen

  class rv_dm_regs_reg_late_debug_enable extends dv_base_reg;
    // fields
    rand dv_base_reg_field late_debug_enable;

    `uvm_object_utils(rv_dm_regs_reg_late_debug_enable)

    function new(string       name = "",
                 int unsigned n_bits = 32,
                 int          has_coverage = UVM_NO_COVERAGE);
      super.new(name, n_bits, has_coverage);
    endfunction : new

    virtual function void build(csr_excl_item csr_excl = null);
      late_debug_enable =
          (dv_base_reg_field::
           type_id::create("late_debug_enable"));
      late_debug_enable.configure(
        .parent(this),
        .size(32),
        .lsb_pos(0),
        .access("RW"),
        .mubi_access("RW"),
        .volatile(0),
        .reset(32'h69696969),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));

      late_debug_enable.set_original_access("RW");
      late_debug_enable.set_mubi_width(32);
    endfunction : build
  endclass : rv_dm_regs_reg_late_debug_enable

  class rv_dm_regs_reg_block extends dv_base_reg_block;
    // registers
    rand rv_dm_regs_reg_alert_test alert_test;
    rand rv_dm_regs_reg_late_debug_enable_regwen late_debug_enable_regwen;
    rand rv_dm_regs_reg_late_debug_enable late_debug_enable;

    `uvm_object_utils(rv_dm_regs_reg_block)

    function new(string name = "",
                 int    has_coverage = UVM_NO_COVERAGE);
      super.new(name, has_coverage);
    endfunction : new

    virtual function void build(uvm_reg_addr_t base_addr,
                                csr_excl_item csr_excl = null);
      // create default map
      this.default_map = create_map(.name("default_map"),
                                    .base_addr(base_addr),
                                    .n_bytes(4),
                                    .endian(UVM_LITTLE_ENDIAN));
      if (csr_excl == null) begin
        csr_excl = csr_excl_item::type_id::create("csr_excl");
        this.csr_excl = csr_excl;
      end
      set_hdl_path_root("tb.dut", "BkdrRegPathRtl");
      set_hdl_path_root("tb.dut", "BkdrRegPathRtlShadow");
      // create registers
      alert_test =
          (rv_dm_regs_reg_alert_test::
           type_id::create("alert_test"));
      alert_test.configure(.blk_parent(this));
      alert_test.build(csr_excl);
      default_map.add_reg(.rg(alert_test),
                          .offset(32'h0));
      alert_test.add_hdl_path_slice(
          "u_reg_regs.u_alert_test.qs",
          0, 1, 0, "BkdrRegPathRtl");

      late_debug_enable_regwen =
          (rv_dm_regs_reg_late_debug_enable_regwen::
           type_id::create("late_debug_enable_regwen"));
      late_debug_enable_regwen.configure(.blk_parent(this));
      late_debug_enable_regwen.build(csr_excl);
      default_map.add_reg(.rg(late_debug_enable_regwen),
                          .offset(32'h4));
      late_debug_enable_regwen.add_hdl_path_slice(
          "u_reg_regs.u_late_debug_enable_regwen.q",
          0, 1, 0, "BkdrRegPathRtl");

      late_debug_enable =
          (rv_dm_regs_reg_late_debug_enable::
           type_id::create("late_debug_enable"));
      late_debug_enable.configure(.blk_parent(this));
      late_debug_enable.build(csr_excl);
      default_map.add_reg(.rg(late_debug_enable),
                          .offset(32'h8));
      late_debug_enable.add_hdl_path_slice(
          "u_reg_regs.u_late_debug_enable.q",
          0, 32, 0, "BkdrRegPathRtl");

      // assign locked reg to its regwen reg
      late_debug_enable_regwen.add_lockable_reg_or_fld(late_debug_enable);


      // Create functional coverage for comportable IP-specific specialized registers.
      // This function can only be called if it is a root block to get the correct gating condition
      // and avoid creating duplicated cov.
      if (this.get_parent() == null && en_dv_reg_cov) create_cov();
    endfunction : build
  endclass : rv_dm_regs_reg_block

endpackage

