#pragma once
#include <cstdint>
#include <cstddef>
struct csr_name_offset { const char *name; uint32_t addr; };
namespace scdv {
  static constexpr csr_name_offset csr_map[] = {
  { "INTR_STATE", 0 },
  { "INTR_ENABLE", 4 },
  { "INTR_TEST", 8 },
  { "ALERT_TEST", 12 },
  { "ME_REGWEN", 0 },
  { "SW_REGUPD", 4 },
  { "REGWEN", 8 },
  { "MODULE_ENABLE", 12 },
  { "CONF", 16 },
  { "ENTROPY_CONTROL", 20 },
  { "ENTROPY_DATA", 24 },
  { "HEALTH_TEST_WINDOWS", 28 },
  { "REPCNT_THRESHOLDS", 32 },
  { "REPCNTS_THRESHOLDS", 36 },
  { "ADAPTP_HI_THRESHOLDS", 40 },
  { "ADAPTP_LO_THRESHOLDS", 44 },
  { "BUCKET_THRESHOLDS", 48 },
  { "MARKOV_HI_THRESHOLDS", 52 },
  { "MARKOV_LO_THRESHOLDS", 56 },
  { "EXTHT_HI_THRESHOLDS", 60 },
  { "EXTHT_LO_THRESHOLDS", 64 },
  { "REPCNT_HI_WATERMARKS", 68 },
  { "REPCNTS_HI_WATERMARKS", 72 },
  { "ADAPTP_HI_WATERMARKS", 76 },
  { "ADAPTP_LO_WATERMARKS", 80 },
  { "EXTHT_HI_WATERMARKS", 84 },
  { "EXTHT_LO_WATERMARKS", 88 },
  { "BUCKET_HI_WATERMARKS", 92 },
  { "MARKOV_HI_WATERMARKS", 96 },
  { "MARKOV_LO_WATERMARKS", 100 },
  { "REPCNT_TOTAL_FAILS", 104 },
  { "REPCNTS_TOTAL_FAILS", 108 },
  { "ADAPTP_HI_TOTAL_FAILS", 112 },
  { "ADAPTP_LO_TOTAL_FAILS", 116 },
  { "BUCKET_TOTAL_FAILS", 120 },
  { "MARKOV_HI_TOTAL_FAILS", 124 },
  { "MARKOV_LO_TOTAL_FAILS", 128 },
  { "EXTHT_HI_TOTAL_FAILS", 132 },
  { "EXTHT_LO_TOTAL_FAILS", 136 },
  { "ALERT_THRESHOLD", 140 },
  { "ALERT_SUMMARY_FAIL_COUNTS", 144 },
  { "ALERT_FAIL_COUNTS", 148 },
  { "EXTHT_FAIL_COUNTS", 152 },
  { "FW_OV_CONTROL", 156 },
  { "FW_OV_SHA3_START", 160 },
  { "FW_OV_WR_FIFO_FULL", 164 },
  { "FW_OV_RD_FIFO_OVERFLOW", 168 },
  { "FW_OV_RD_DATA", 172 },
  { "FW_OV_WR_DATA", 176 },
  { "OBSERVE_FIFO_THRESH", 180 },
  { "OBSERVE_FIFO_DEPTH", 184 },
  { "DEBUG_STATUS", 188 },
  { "RECOV_ALERT_STS", 192 },
  { "ERR_CODE", 196 },
  { "ERR_CODE_TEST", 200 },
  { "MAIN_SM_STATE", 204 }
  };
  static constexpr std::size_t csr_map_size = sizeof(csr_map)/sizeof(csr_map[0]);
}
