// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// UVM Registers auto-generated by `reggen` containing data structure
package soc_dbg_ctrl_core_ral_pkg;
  // dep packages
  import uvm_pkg::*;
  import dv_base_reg_pkg::*;

  // macro includes
  `include "uvm_macros.svh"

  // Forward declare all register/memory/block classes
  typedef class soc_dbg_ctrl_core_reg_alert_test;
  typedef class soc_dbg_ctrl_core_reg_debug_policy_valid_shadowed;
  typedef class soc_dbg_ctrl_core_reg_debug_policy_category_shadowed;
  typedef class soc_dbg_ctrl_core_reg_debug_policy_relocked;
  typedef class soc_dbg_ctrl_core_reg_trace_debug_policy_category;
  typedef class soc_dbg_ctrl_core_reg_trace_debug_policy_valid_relocked;
  typedef class soc_dbg_ctrl_core_reg_status;
  typedef class soc_dbg_ctrl_core_reg_block;

  class soc_dbg_ctrl_core_reg_alert_test extends dv_base_reg;
    // fields
    rand dv_base_reg_field fatal_fault;
    rand dv_base_reg_field recov_ctrl_update_err;

    `uvm_object_utils(soc_dbg_ctrl_core_reg_alert_test)

    function new(string       name = "",
                 int unsigned n_bits = 32,
                 int          has_coverage = UVM_NO_COVERAGE);
      super.new(name, n_bits, has_coverage);
    endfunction : new

    virtual function void build(csr_excl_item csr_excl = null);
      fatal_fault =
          (dv_base_reg_field::
           type_id::create("fatal_fault"));
      fatal_fault.configure(
        .parent(this),
        .size(1),
        .lsb_pos(0),
        .access("WO"),
        .mubi_access("NONE"),
        .volatile(0),
        .reset(32'h0),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));

      fatal_fault.set_original_access("WO");
      recov_ctrl_update_err =
          (dv_base_reg_field::
           type_id::create("recov_ctrl_update_err"));
      recov_ctrl_update_err.configure(
        .parent(this),
        .size(1),
        .lsb_pos(1),
        .access("WO"),
        .mubi_access("NONE"),
        .volatile(0),
        .reset(32'h0),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));

      recov_ctrl_update_err.set_original_access("WO");
      set_is_ext_reg(1);
    endfunction : build
  endclass : soc_dbg_ctrl_core_reg_alert_test

  class soc_dbg_ctrl_core_reg_debug_policy_valid_shadowed extends dv_base_reg;
    // fields
    rand dv_base_reg_field debug_policy_valid;

    `uvm_object_utils(soc_dbg_ctrl_core_reg_debug_policy_valid_shadowed)

    function new(string       name = "",
                 int unsigned n_bits = 32,
                 int          has_coverage = UVM_NO_COVERAGE);
      super.new(name, n_bits, has_coverage);
    endfunction : new

    virtual function void build(csr_excl_item csr_excl = null);
      debug_policy_valid =
          (dv_base_reg_field::
           type_id::create("debug_policy_valid"));
      debug_policy_valid.configure(
        .parent(this),
        .size(4),
        .lsb_pos(0),
        .access("RW"),
        .mubi_access("W1S"),
        .volatile(0),
        .reset(32'h9),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));

      debug_policy_valid.set_original_access("RW");
      debug_policy_valid.set_mubi_width(4);
    endfunction : build
  endclass : soc_dbg_ctrl_core_reg_debug_policy_valid_shadowed

  class soc_dbg_ctrl_core_reg_debug_policy_category_shadowed extends dv_base_reg;
    // fields
    rand dv_base_reg_field debug_policy_category;

    `uvm_object_utils(soc_dbg_ctrl_core_reg_debug_policy_category_shadowed)

    function new(string       name = "",
                 int unsigned n_bits = 32,
                 int          has_coverage = UVM_NO_COVERAGE);
      super.new(name, n_bits, has_coverage);
    endfunction : new

    virtual function void build(csr_excl_item csr_excl = null);
      debug_policy_category =
          (dv_base_reg_field::
           type_id::create("debug_policy_category"));
      debug_policy_category.configure(
        .parent(this),
        .size(7),
        .lsb_pos(0),
        .access("RW"),
        .mubi_access("NONE"),
        .volatile(1),
        .reset(32'h50),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));

      debug_policy_category.set_original_access("RW");
      // create field tags
      set_is_ext_reg(1);
    endfunction : build
  endclass : soc_dbg_ctrl_core_reg_debug_policy_category_shadowed

  class soc_dbg_ctrl_core_reg_debug_policy_relocked extends dv_base_reg;
    // fields
    rand dv_base_reg_field debug_policy_relocked;

    `uvm_object_utils(soc_dbg_ctrl_core_reg_debug_policy_relocked)

    function new(string       name = "",
                 int unsigned n_bits = 32,
                 int          has_coverage = UVM_NO_COVERAGE);
      super.new(name, n_bits, has_coverage);
    endfunction : new

    virtual function void build(csr_excl_item csr_excl = null);
      debug_policy_relocked =
          (dv_base_reg_field::
           type_id::create("debug_policy_relocked"));
      debug_policy_relocked.configure(
        .parent(this),
        .size(4),
        .lsb_pos(0),
        .access("RW"),
        .mubi_access("RW"),
        .volatile(0),
        .reset(32'h9),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));

      debug_policy_relocked.set_original_access("RW");
      debug_policy_relocked.set_mubi_width(4);
    endfunction : build
  endclass : soc_dbg_ctrl_core_reg_debug_policy_relocked

  class soc_dbg_ctrl_core_reg_trace_debug_policy_category extends dv_base_reg;
    // fields
    rand dv_base_reg_field category;

    `uvm_object_utils(soc_dbg_ctrl_core_reg_trace_debug_policy_category)

    function new(string       name = "",
                 int unsigned n_bits = 32,
                 int          has_coverage = UVM_NO_COVERAGE);
      super.new(name, n_bits, has_coverage);
    endfunction : new

    virtual function void build(csr_excl_item csr_excl = null);
      category =
          (dv_base_reg_field::
           type_id::create("category"));
      category.configure(
        .parent(this),
        .size(7),
        .lsb_pos(0),
        .access("RO"),
        .mubi_access("NONE"),
        .volatile(1),
        .reset(32'h50),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));

      category.set_original_access("RO");
    endfunction : build
  endclass : soc_dbg_ctrl_core_reg_trace_debug_policy_category

  class soc_dbg_ctrl_core_reg_trace_debug_policy_valid_relocked extends dv_base_reg;
    // fields
    rand dv_base_reg_field valid;
    rand dv_base_reg_field relocked;

    `uvm_object_utils(soc_dbg_ctrl_core_reg_trace_debug_policy_valid_relocked)

    function new(string       name = "",
                 int unsigned n_bits = 32,
                 int          has_coverage = UVM_NO_COVERAGE);
      super.new(name, n_bits, has_coverage);
    endfunction : new

    virtual function void build(csr_excl_item csr_excl = null);
      valid =
          (dv_base_reg_field::
           type_id::create("valid"));
      valid.configure(
        .parent(this),
        .size(4),
        .lsb_pos(0),
        .access("RO"),
        .mubi_access("RO"),
        .volatile(1),
        .reset(32'h9),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));

      valid.set_original_access("RO");
      valid.set_mubi_width(4);
      relocked =
          (dv_base_reg_field::
           type_id::create("relocked"));
      relocked.configure(
        .parent(this),
        .size(4),
        .lsb_pos(4),
        .access("RO"),
        .mubi_access("RO"),
        .volatile(1),
        .reset(32'h9),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));

      relocked.set_original_access("RO");
      relocked.set_mubi_width(4);
    endfunction : build
  endclass : soc_dbg_ctrl_core_reg_trace_debug_policy_valid_relocked

  class soc_dbg_ctrl_core_reg_status extends dv_base_reg;
    // fields
    rand dv_base_reg_field auth_debug_intent_set;
    rand dv_base_reg_field auth_window_open;
    rand dv_base_reg_field auth_window_closed;
    rand dv_base_reg_field auth_unlock_success;
    rand dv_base_reg_field auth_unlock_failed;

    `uvm_object_utils(soc_dbg_ctrl_core_reg_status)

    function new(string       name = "",
                 int unsigned n_bits = 32,
                 int          has_coverage = UVM_NO_COVERAGE);
      super.new(name, n_bits, has_coverage);
    endfunction : new

    virtual function void build(csr_excl_item csr_excl = null);
      auth_debug_intent_set =
          (dv_base_reg_field::
           type_id::create("auth_debug_intent_set"));
      auth_debug_intent_set.configure(
        .parent(this),
        .size(1),
        .lsb_pos(0),
        .access("RW"),
        .mubi_access("NONE"),
        .volatile(0),
        .reset(32'h0),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));

      auth_debug_intent_set.set_original_access("RW");
      auth_window_open =
          (dv_base_reg_field::
           type_id::create("auth_window_open"));
      auth_window_open.configure(
        .parent(this),
        .size(1),
        .lsb_pos(4),
        .access("RW"),
        .mubi_access("NONE"),
        .volatile(0),
        .reset(32'h0),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));

      auth_window_open.set_original_access("RW");
      auth_window_closed =
          (dv_base_reg_field::
           type_id::create("auth_window_closed"));
      auth_window_closed.configure(
        .parent(this),
        .size(1),
        .lsb_pos(5),
        .access("RW"),
        .mubi_access("NONE"),
        .volatile(0),
        .reset(32'h0),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));

      auth_window_closed.set_original_access("RW");
      auth_unlock_success =
          (dv_base_reg_field::
           type_id::create("auth_unlock_success"));
      auth_unlock_success.configure(
        .parent(this),
        .size(1),
        .lsb_pos(6),
        .access("RW"),
        .mubi_access("NONE"),
        .volatile(0),
        .reset(32'h0),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));

      auth_unlock_success.set_original_access("RW");
      auth_unlock_failed =
          (dv_base_reg_field::
           type_id::create("auth_unlock_failed"));
      auth_unlock_failed.configure(
        .parent(this),
        .size(1),
        .lsb_pos(7),
        .access("RW"),
        .mubi_access("NONE"),
        .volatile(0),
        .reset(32'h0),
        .has_reset(1),
        .is_rand(1),
        .individually_accessible(1));

      auth_unlock_failed.set_original_access("RW");
    endfunction : build
  endclass : soc_dbg_ctrl_core_reg_status

  class soc_dbg_ctrl_core_reg_block extends dv_base_reg_block;
    // registers
    rand soc_dbg_ctrl_core_reg_alert_test alert_test;
    rand soc_dbg_ctrl_core_reg_debug_policy_valid_shadowed debug_policy_valid_shadowed;
    rand soc_dbg_ctrl_core_reg_debug_policy_category_shadowed debug_policy_category_shadowed;
    rand soc_dbg_ctrl_core_reg_debug_policy_relocked debug_policy_relocked;
    rand soc_dbg_ctrl_core_reg_trace_debug_policy_category trace_debug_policy_category;
    rand soc_dbg_ctrl_core_reg_trace_debug_policy_valid_relocked trace_debug_policy_valid_relocked;
    rand soc_dbg_ctrl_core_reg_status status;

    `uvm_object_utils(soc_dbg_ctrl_core_reg_block)

    function new(string name = "",
                 int    has_coverage = UVM_NO_COVERAGE);
      super.new(name, has_coverage);
    endfunction : new

    virtual function void build(uvm_reg_addr_t base_addr,
                                csr_excl_item csr_excl = null);
      // create default map
      this.default_map = create_map(.name("default_map"),
                                    .base_addr(base_addr),
                                    .n_bytes(4),
                                    .endian(UVM_LITTLE_ENDIAN));
      if (csr_excl == null) begin
        csr_excl = csr_excl_item::type_id::create("csr_excl");
        this.csr_excl = csr_excl;
      end
      set_hdl_path_root("tb.dut", "BkdrRegPathRtl");
      set_hdl_path_root("tb.dut", "BkdrRegPathRtlShadow");
      // create registers
      alert_test =
          (soc_dbg_ctrl_core_reg_alert_test::
           type_id::create("alert_test"));
      alert_test.configure(.blk_parent(this));
      alert_test.build(csr_excl);
      default_map.add_reg(.rg(alert_test),
                          .offset(32'h0));
      alert_test.add_hdl_path_slice(
          "u_reg_core.u_alert_test_fatal_fault.qs",
          0, 1, 0, "BkdrRegPathRtl");
      alert_test.add_hdl_path_slice(
          "u_reg_core.u_alert_test_recov_ctrl_update_err.qs",
          1, 1, 0, "BkdrRegPathRtl");

      debug_policy_valid_shadowed =
          (soc_dbg_ctrl_core_reg_debug_policy_valid_shadowed::
           type_id::create("debug_policy_valid_shadowed"));
      debug_policy_valid_shadowed.configure(.blk_parent(this));
      debug_policy_valid_shadowed.build(csr_excl);
      default_map.add_reg(.rg(debug_policy_valid_shadowed),
                          .offset(32'h4));
      debug_policy_valid_shadowed.add_update_err_alert("recov_ctrl_update_err");

      debug_policy_valid_shadowed.add_storage_err_alert("fatal_fault");

      debug_policy_valid_shadowed.add_hdl_path_slice(
          "u_reg_core.u_debug_policy_valid_shadowed.committed_reg.q",
          0, 4, 0, "BkdrRegPathRtl");
      debug_policy_valid_shadowed.add_hdl_path_slice(
          "u_reg_core.u_debug_policy_valid_shadowed.shadow_reg.q",
          0, 4, 0, "BkdrRegPathRtlShadow");

      debug_policy_valid_shadowed.set_is_shadowed();
      // create register tags
      csr_excl.add_excl(debug_policy_valid_shadowed.get_full_name(),
                        CsrExclWrite, CsrNonInitTests);
      debug_policy_category_shadowed =
          (soc_dbg_ctrl_core_reg_debug_policy_category_shadowed::
           type_id::create("debug_policy_category_shadowed"));
      debug_policy_category_shadowed.configure(.blk_parent(this));
      debug_policy_category_shadowed.build(csr_excl);
      default_map.add_reg(.rg(debug_policy_category_shadowed),
                          .offset(32'h8));
      debug_policy_category_shadowed.add_update_err_alert("recov_ctrl_update_err");

      debug_policy_category_shadowed.add_storage_err_alert("fatal_fault");

      debug_policy_category_shadowed.add_hdl_path_slice(
          "u_debug_policy_category_shadowed.committed_reg.q", // verilog_lint: waive line-length
          0, 7, 0, "BkdrRegPathRtl");
      debug_policy_category_shadowed.add_hdl_path_slice(
          "u_debug_policy_category_shadowed.shadow_reg.q", // verilog_lint: waive line-length
          0, 7, 0, "BkdrRegPathRtlShadow");

      debug_policy_category_shadowed.set_is_shadowed();
      debug_policy_relocked =
          (soc_dbg_ctrl_core_reg_debug_policy_relocked::
           type_id::create("debug_policy_relocked"));
      debug_policy_relocked.configure(.blk_parent(this));
      debug_policy_relocked.build(csr_excl);
      default_map.add_reg(.rg(debug_policy_relocked),
                          .offset(32'hc));
      debug_policy_relocked.add_hdl_path_slice(
          "u_reg_core.u_debug_policy_relocked.q",
          0, 4, 0, "BkdrRegPathRtl");

      trace_debug_policy_category =
          (soc_dbg_ctrl_core_reg_trace_debug_policy_category::
           type_id::create("trace_debug_policy_category"));
      trace_debug_policy_category.configure(.blk_parent(this));
      trace_debug_policy_category.build(csr_excl);
      default_map.add_reg(.rg(trace_debug_policy_category),
                          .offset(32'h10));
      trace_debug_policy_category.add_hdl_path_slice(
          "u_reg_core.u_trace_debug_policy_category.q",
          0, 7, 0, "BkdrRegPathRtl");

      trace_debug_policy_valid_relocked =
          (soc_dbg_ctrl_core_reg_trace_debug_policy_valid_relocked::
           type_id::create("trace_debug_policy_valid_relocked"));
      trace_debug_policy_valid_relocked.configure(.blk_parent(this));
      trace_debug_policy_valid_relocked.build(csr_excl);
      default_map.add_reg(.rg(trace_debug_policy_valid_relocked),
                          .offset(32'h14));
      trace_debug_policy_valid_relocked.add_hdl_path_slice(
          "u_reg_core.u_trace_debug_policy_valid_relocked_valid.q",
          0, 4, 0, "BkdrRegPathRtl");
      trace_debug_policy_valid_relocked.add_hdl_path_slice(
          "u_reg_core.u_trace_debug_policy_valid_relocked_relocked.q",
          4, 4, 0, "BkdrRegPathRtl");

      status =
          (soc_dbg_ctrl_core_reg_status::
           type_id::create("status"));
      status.configure(.blk_parent(this));
      status.build(csr_excl);
      default_map.add_reg(.rg(status),
                          .offset(32'h18));
      status.add_hdl_path_slice(
          "u_reg_core.u_status_auth_debug_intent_set.q",
          0, 1, 0, "BkdrRegPathRtl");
      status.add_hdl_path_slice(
          "u_reg_core.u_status_auth_window_open.q",
          4, 1, 0, "BkdrRegPathRtl");
      status.add_hdl_path_slice(
          "u_reg_core.u_status_auth_window_closed.q",
          5, 1, 0, "BkdrRegPathRtl");
      status.add_hdl_path_slice(
          "u_reg_core.u_status_auth_unlock_success.q",
          6, 1, 0, "BkdrRegPathRtl");
      status.add_hdl_path_slice(
          "u_reg_core.u_status_auth_unlock_failed.q",
          7, 1, 0, "BkdrRegPathRtl");



      // Create functional coverage for comportable IP-specific specialized registers.
      // This function can only be called if it is a root block to get the correct gating condition
      // and avoid creating duplicated cov.
      if (this.get_parent() == null && en_dv_reg_cov) create_cov();
    endfunction : build
  endclass : soc_dbg_ctrl_core_reg_block

endpackage

